### ISSUE TITLE
Mode issue with night mode.

### ISSUE THREAD

**Issue by ghuser9822** [Xacnio/tweetcapture#10]
If we call screenshot method with mode=0, night_mode=2

It should produce this output black with no extra details :

![image](https://user-images.githubusercontent.com/114803859/193449301-ae2a68c0-e347-4c99-a8e3-46c497234a2d.png)

but out put is throwing this :

![image](https://user-images.githubusercontent.com/114803859/193449343-c81ec463-a57f-41c9-9aa6-800940c4d013.png)

There might be issue with init method in screenshot.py

I recommend you to test all modes and night modes.

**Comment by Xacnio** [comment]
Please share the tweetcapture part of your code, maybe you have wrong use. The package has no problem, i have just tried.

**Modes 0-4:**

![tweet-m0-n2](https://user-images.githubusercontent.com/49660313/193450758-b0491095-3756-4cfa-aa0b-0afe33459f5f.png)

![tweet-m1-n2](https://user-images.githubusercontent.com/49660313/193450751-b07019f6-024c-4109-8c71-1a94802452d2.png)

![tweet-m2-n2](https://user-images.githubusercontent.com/49660313/193450754-8583696d-4c57-4c22-84e2-c395020753e3.png)

![tweet-m3-n2](https://user-images.githubusercontent.com/49660313/193450755-3aa99dc8-df58-4786-b3d8-247dceb4b0ae.png)

![tweet-m4-n2](https://user-images.githubusercontent.com/49660313/193450757-0f976d14-6a43-464e-85cc-12d1e3f68301.png)

**Comment by ghuser9822** [comment]
path = await tweet.screenshot(tweet_url, "testig.png", mode=0, night_mode=2)

output : 

![image](https://user-images.githubusercontent.com/114803859/193451677-8ae59d2d-0a0d-4364-bbc2-083c290eae11.png)

it should be : 

![image](https://user-images.githubusercontent.com/114803859/193451707-c56a9be7-f170-416e-b671-fb2708046c40.png)

am i passing correct parameters ?

![image](https://user-images.githubusercontent.com/114803859/193451764-e8b8efcb-246d-4bc9-9064-32c8479d3c2e.png)

**Comment by Xacnio** [comment]
Thanks. It was relevant with the arguments and conditions of screenshot function. Fixed. Upgrade: `pip3 install -U tweet-capture`
