### ISSUE TITLE
Show parent tweets (-sp) error when parent tweet is unavailable

### ISSUE THREAD

**Issue by thalljoben** [Xacnio/tweetcapture#21]
Thank you for the recent updates (show parent and overwrite logic), both updates made this tool more robust.

I encountered an issue with the show parent (-sp) argument. I am running tweetcapture -sp in a loop, capturing multiple tweets. I have found that tweetcapture with the -sp argument fails to capture a screenshot when the parent tweet is no longer available. Is it possible to augment this program to account for this scenario? (Ideally, capture a screenshot with the error message that Twitter provides, showing that the parent tweet is no longer available. Or default back to a single, non-parent screenshot)

Here are three scenarios I encountered, with the parent tweet unavailable for three different reasons. They all generate the same error message:

Scenario 1:
A parent tweet is unavailable due to condition: "You’re unable to view this Tweet because this account owner limits who can view their Tweets. Learn more"
tweetcapture -sp https://twitter.com/gerardway/status/746382756918091777

Scenario 2:
A parent tweet is unavailable due to condition: "This Tweet is unavailable. Learn more"
tweetcapture -sp https://twitter.com/gerardway/status/744158517179744258

Scenario 3:
A parent tweet is unavailable due to condition "This Tweet was deleted by the Tweet author. Learn more"
https://twitter.com/jack/status/1593080961969049600

All scenarios return this error message via tweetcapture -sp:
Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.r-1ta3fxp"}
  (Session info: headless chrome=107.0.5304.107)

Thank you

**Comment by Xacnio** [comment]
It's all right now. #22
<details>
    <summary>Images</summary>
    <img src="https://user-images.githubusercontent.com/49660313/203209987-bb1d540d-aa03-47a8-b71d-955201c66fb0.png" />
    <img src="https://user-images.githubusercontent.com/49660313/203209991-c4b2111b-c3aa-4647-a8a7-bb0a33cea738.png" />
   <img src="https://user-images.githubusercontent.com/49660313/203209993-372d784d-750c-4e91-9a64-b4bcaa0043df.png" />
</details>
