### ISSUE TITLE
Argument or mode to hide twitter integrations and assets

### ISSUE THREAD

**Issue by Erim32** [Xacnio/tweetcapture#23]
Great work @Xacnio 👍, just a missing option to have a perfect tool.
**Could you please add an option to hide twitter integrations ( links cards, images, videos, gifs...) ?**

Note : an option to have round corners in output files can be a nice to have for a future version.

Regards

**Comment by Xacnio** [comment]
Thanks for requests.

Screenshots that have rounded corner #27 
Hide tweet medias: #28
