### ISSUE TITLE
Error message: 'chromedriver' exec. needs to be in PATH

### ISSUE THREAD

**Issue by quirsh** [Xacnio/tweetcapture#26]
Hi,

when i try to run tweetcapture from the command line I get this message and now file is created:

`Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home`

Chromedriver is installed and seems to be in the within one of the PATH-directories as I can call it from the same spot in the command line. 

Thanks for the help in advance!

**Comment by Xacnio** [comment]
Use [--chromedriver CHROMEDRIVER] argument. 
Example
`tweetcapture --chromedriver /usr/bin/chromedriver <tweet-url>`
