### ISSUE TITLE
🐞 Bug : modes not working with screenshot method.

### ISSUE THREAD

**Issue by Erim32** [Xacnio/tweetcapture#29]
Thank you for new features discuss in the previous issue.

I just identified a bug, with "mode", they are not working when user want to get a screenshot of only one tweet using the screenshot( ) method ( python usage, not CLI ).

Tweet used for test : https://twitter.com/JagoeCapital/status/1598454780355026945

The issue is probably related to this condition, by but variables are not explicit, I will let you check : ( never seems to be true)
https://github.com/Xacnio/tweetcapture/blob/790ca13b322c4ac7454de999d2a78150f95ef34d/tweetcapture/screenshot.py#L73

**Comment by Xacnio** [comment]
Thanks. I'll fix it as soon.
