### ISSUE TITLE
How do I create an API from this?

### ISSUE THREAD

**Issue by pooriaarab** [Xacnio/tweetcapture#3]
Working on tweet -> screenshot -> instagram

And wanted to create an API from this repo. 

Tips and directions on how to do it is appreciated. 

Can submit PR request once done

**Comment by Xacnio** [comment]
Added [tweet_screenshot_to_instagram.py](https://github.com/Xacnio/tweetcapture/blob/main/tweetcapture/examples/tweet_screenshot_to_instagram.py) to examples

Used for Instagram Uploading: https://github.com/adw0rd/instagrapi
Optionally, another module can be used for IG uploading.

<details>
  <summary>Images:</summary>
  <img src="https://user-images.githubusercontent.com/49660313/174802296-9e986f4c-30f5-4f8f-9d8d-f4c961d05cdd.png" width="300" />
  <img src="https://user-images.githubusercontent.com/49660313/174802302-339e0ad1-1320-4d7b-ab58-ef3a4288ecb4.png" width="600"> 
</summary>
