### ISSUE TITLE
Improve scale and quality

### ISSUE THREAD

**Issue by PitaHat** [xacnio/tweetcapture#35]
Hello!

Really neat tool that works best out of the all other open source solutions. However, is there any way to improve the screenshots' quality?

Thank you

**Comment by xacnio** [comment]
Hello,

Screenshot quality is enough for the module. Maybe the window resolution can be increased. But Twitter has maximum width/height settings on design, I guess screenshot quality will be the same.

`chrome_options.add_argument("--window-size=768,2000");`
