### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Potracheno** [xacnio/tweetcapture#36]
I try to use proxy this way `export HTTP_PROXY=socks5://ip:port` but no luck.
Can you add proxy support please ?

**Comment by xacnio** [comment]
You can use the chrome option. But it has no authentication.

https://www.chromium.org/developers/design-documents/network-settings/
https://www.chromium.org/developers/design-documents/network-stack/socks-proxy/

```
tweet = TweetCapture()
# tweet.add_chrome_argument('--proxy-server=127.0.0.1:3128')
tweet.add_chrome_argument('--proxy-server=socks5://myproxy:8080')
```

_it's only code usage. tweetcapture cli has no argument to adding chrome argument for now._
