### ISSUE TITLE
How can I make the name of the screenshot a url name?

### ISSUE THREAD

**Issue by ilkeronurisik** [xacnio/tweetcapture#39]
There is a parameter named Path, I saw that. But I have a url dataframe. 

1-I want the names of the screenshots I save to be the same as the url names in a loop. 
2-And I want to choose the folder where I will save it.

**ss_tweet     ------>>>my dataframe**
Out[74]: 
1465    https://twitter.com/selmanogut/status/16252638...
3713    https://twitter.com/yanbasan_osman/status/1625...
Name: url, dtype: object

from tweetcapture import TweetCapture
import asyncio
tweet = TweetCapture()
for i in ss_tweet:
    asyncio.run(tweet.screenshot(i, mode=3, night_mode=2))

**Comment by xacnio** [comment]
You can specify a folder in "path". 

`asyncio.run(tweet.screenshot(i, mode=3, night_mode=2, path="folder1/folder2/folder3/image.png"))`

But directories must be exist. You can create with `os.mkdir` before the taking tweet screenshot.

There isn't any macros or functions for filenames. You can extract the username or the tweet ID from URL.
```python
from re import match

url = "https://twitter.com/jack/status/20"
result = match("^https?:\/\/([A-Za-z0-9.]+)?twitter\.com\/(?:#!\/)?(\w+)\/status(es)?\/(\d+)", url)
username = result[2] # jack
tweetId = result[4] # 20
```
