### ISSUE TITLE
support screenshotting tweets without an account?

### ISSUE THREAD

**Issue by jadedgnome** [xacnio/tweetcapture#44]
For tweet links: https://platform.twitter.com/embed/Tweet.html?id=TWEET_ID (replace TWEET_ID with the number of a tweet URL)

**Comment by xacnio** [comment]
Thanks for the request.

The module is made for screenshot the main tweet components. I think support embed tweet screenshots would be very complex in the project and there are already many projects as tweet image generator with embed, you can use them.
