### ISSUE TITLE
username and tweet ID no longer is saved as filename.

### ISSUE THREAD

**Issue by jadedgnome** [xacnio/tweetcapture#49]
any twitter url i pass to the script results in this.

Screenshot is saved: @twitter.com_None_tweetcapture.png

so I end up with filename already exists message with each new URL I try to screenshot.

**Comment by xacnio** [comment]
Sorry, i'm late.

Fixed on 0.2.2, update the module.  `pip3 install -U tweet-capture`

Commit: https://github.com/xacnio/tweetcapture/commit/e57ab58467baa3e99bff1c838d902190a87518fa

Also the docker image just updated:
https://hub.docker.com/r/xacnio/tweetcapture
