### ISSUE TITLE
Image is not saved

### ISSUE THREAD

**Issue by HyperTesseract** [Xacnio/tweetcapture#5]
Hey there,
I am running your project on mac and everything runs through but the image is not saved anywhere, at least I can't find it. Any suggestion?

Thanks in advance

**Comment by Xacnio** [comment]
Can you try full path for output?
Example on Cli:
```
tweetcapture https://twitter.com/jack/status/20 -o /Users/username/Desktop/test.png
```

**Comment by HyperTesseract** [comment]
Same, still no image 🤷‍♂️

**Comment by Xacnio** [comment]
I'll try to examine it. I haven't Mac so it will be hard for me. Thanks for reporting the issue.

**Comment by Xacnio** [comment]
Thanks again, fixed. <a href="/Xacnio/tweetcapture/releases/tag/0.0.12">Release: 0.0.12</a>

**Comment by Lux-verit** [comment]
I have a Mac and am facing the same issue

**Comment by Xacnio** [comment]
> I have a Mac and am facing the same issue
Did you upgrade the package?
```
> pip3 install -U tweet-capture
> pip3 install -U selenium
```
There was a problem but it should be working on 0.0.13.

macOS test on 0.0.13:
https://github.com/Xacnio/tweetcapture/runs/7570222675?check_suite_focus=true
https://github.com/Xacnio/tweetcapture/suites/7571257875/artifacts/313009601
