### ISSUE TITLE
[Request] Retina-quality screenshots

### ISSUE THREAD

**Issue by pjburnhill** [xacnio/tweetcapture#51]
Well done for a great lib.

Any chance of a retina-quality capture?

**Comment by xacnio** [comment]
The lib is use a real browser with selenium and capture posts' node screenshot. Post width is 598px (by X / Twitter) and its not changing with resolution increasing. So, custom css code is required to increase screenshot quality but it can disrupt some features. CSS's scale feature can be used. I'm gonna try it.

**Comment by pjburnhill** [comment]
Ah thanks for the clarification. Not a big issue, just thought maybe there was an easy fix. Thanks for looking into it.
