### ISSUE TITLE
[Request] Replace 'Follow' with X logo

### ISSUE THREAD

**Issue by pjburnhill** [xacnio/tweetcapture#52]
Would be great if the 'Follow' button (upper right) was replaced with the X logo:

**tweetcapture:**
![@KenneyNL_1706620696913236079_tweetcapture](https://github.com/xacnio/tweetcapture/assets/2419138/8dafceaa-3a06-40f3-ae8a-a7becde0215e)

**screenshot.guru:**
![1706620696913236079](https://github.com/xacnio/tweetcapture/assets/2419138/dcc4f808-bcd7-4ad2-9d2d-13a8d86913d6)

**Comment by xacnio** [comment]
Because screenshot.guru uses embed version: https://publish.twitter.com/ 
tweetcapture uses real tweet view. The follow button can be hided.

**Comment by pjburnhill** [comment]
Ah thanks for the clarification!

Just checking, can the Follow be hidden in the current version of tweetcapture?

**Comment by xacnio** [comment]
> Ah thanks for the clarification!
> 
> Just checking, can the Follow be hidden in the current version of tweetcapture?

Yes, it can. I'm going to publish after some tests. 

https://github.com/xacnio/tweetcapture/commit/4667b20899694609dc665d9bd5cfd04e3dcb1190

**Comment by pjburnhill** [comment]
Thanks! Tested it myself and seems to work perfectly when I ran it.
