### ISSUE TITLE
How can i print the contents of the tweets?

### ISSUE THREAD

**Issue by ghuser9822** [Xacnio/tweetcapture#8]
Hi want to send text content of tweet as caption to insta.

Can you please help how can i get the contents of the tweet ?

**Comment by Xacnio** [comment]
The package is only to screenshot operations. You can lookup another package for this.

**Comment by ghuser9822** [comment]
there must be tweet contents passing through some variable,

It would be great if you help to access it.

it will help me to add as a caption to insta image.
